server:
  port: 9003

spring:
  application:
    name: view-service

  datasource:
    url: jdbc:mysql://localhost:3306/article_view
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none