server:
  port: 9000

spring:
    application:
        name: article-service

    datasource:
        url: jdbc:mysql://localhost:3307/article
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver


    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: none