server:
  port: 9001

spring:
  application:
    name: comment-service

  datasource:
    url: jdbc:mysql://localhost:3306/comment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 127.0.0.1
  kafka:
    bootstrap-servers: 127.0.0.1:9092